volumes:
  pg_data:
  redis:

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./.dev/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    ports:
      - "5445:5432"

  websocket-service-svc:
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:8080/websocket/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 40s
    ports:
      - "8081:8080"
      - "5081:5005"
    environment:
      - DB_NAME=websocket-db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - JDK_JAVA_OPTIONS=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=a4rT44Rce32w87htRft56
      - REDIS_DATABASE=0
    build:
      context: .
      dockerfile: .dev/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - redis
  angular-app:
    build:
      context: ./src/main/resources/webapp
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src/main/resources/webapp:/app
      - /app/node_modules
  seed:
    image: barrypiccinni/psql-curl
    restart: 'no'
    volumes:
      - ./.dev/seed.sql:/tmp/seed.sql
      - ./.dev/seed.sh:/tmp/seed.sh
    entrypoint: bash -c 'chmod +x /tmp/seed.sh && /tmp/seed.sh && psql -h db -U postgres -d websocket-db -f /tmp/seed.sql'
    environment:
      PGPASSWORD: 12345678
    depends_on:
      websocket-service-svc:
        condition: service_healthy

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "a4rT44Rce32w87htRft56", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --save 20 1 --loglevel warning --requirepass a4rT44Rce32w87htRft56
    volumes:
      - redis:/data