spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

app:
  jwt:
    accessTokenSecret: BvPHGM8C0ia4uOtrxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3KL4lxA9i8bj6OTbadwezxgeEByY
    accessTokenExpirationMs: 3600000