spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration


app:
  jwt:
    accessTokenSecret: BvPHGM8C0ia4uOtrxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3KL4lxA9i8bj6OTbadwezxgeEByY
    accessTokenExpirationMs: 3600000

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
  endpoint:
    health:
      show-details: always