server:
  servlet:
    context-path: /websocket
spring:
  cache:
    type: simple
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5434/websocket-db
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

app:
  jwt:
    accessTokenSecret: BvPHGM8C0ia4uOtrxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3KL4lxA9i8bj6OTbadwezxgeEByY
    accessTokenExpirationMs: 3600000